### ISSUE TITLE
NEW REQUEST: On-demand refresh

### ISSUE THREAD

**Issue by charliesoap4** [michaelwoods/onstar2mqtt#221]
RIght now, you can only set a refresh interval at launch.  Normally, 30min is fine.  Every once in a while, it'd be nice to force a refresh when I choose to.

**Comment by Gibby** [comment]
@charliesoap4 you can.

Here are my scripts for my vehicle, see the last one
```yaml
---

locate_vehicle:
  alias: Locate vehicle
  sequence:
    - service: mqtt.publish
      data:
        topic: homeassistant/VIN_GOES_HERE/command
        payload: '{"command": "getLocation"}'
  mode: single
  icon: 'mdi:map-marker'

start_vehicle:
  alias: vehicle Start Vehicle
  sequence:
    - service: mqtt.publish
      data:
        topic: homeassistant/VIN_GOES_HERE/command
        payload: '{"command": "startVehicle"}'
  mode: single
  icon: 'mdi:car-estate'

stop_vehicle:
  alias: vehicle Cancel Start Vehicle
  sequence:
    - service: mqtt.publish
      data:
        topic: homeassistant/VIN_GOES_HERE/command
        payload: '{"command": "cancelStartVehicle"}'
  mode: single
  icon: 'mdi:car-estate'

unlock_vehicle:
  alias: vehicle Unlock Vehicle
  sequence:
    - service: mqtt.publish
      data:
        topic: homeassistant/VIN_GOES_HERE/command
        payload: '{"command": "unlockDoor"}'
  mode: single
  icon: 'mdi:car-estate'

lock_vehicle:
  alias: Lock vehicle
  sequence:
    - service: mqtt.publish
      data:
        topic: homeassistant/VIN_GOES_HERE/command
        payload: '{"command": "lockDoor"}'
  mode: single
  icon: 'mdi:car-estate'

alarm_vehicle:
  alias: Alarm vehicle
  sequence:
    - service: mqtt.publish
      data:
        topic: homeassistant/VIN_GOES_HERE/command
        payload: '{"command": "alert"}'
  mode: single
  icon: 'mdi:car-estate'

cancel_alarm_vehicle:
  alias: Cancel vehicle Alarm
  sequence:
    - service: mqtt.publish
      data:
        topic: homeassistant/VIN_GOES_HERE/command
        payload: '{"command": "cancelAlert"}'
  mode: single
  icon: 'mdi:car-estate'

update_vehicle_info:
  alias: Update vehicle Info
  sequence:
    - service: mqtt.publish
      data:
        topic: homeassistant/VIN_GOES_HERE/command
        payload: '{"command": "diagnostics"}'
  mode: single
  icon: 'mdi:car-estate'

```


Here is my lovelace
```yaml
---
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: grid
            cards:
              - type: button
                tap_action:
                  action: toggle
                entity: script.start_vehicle
                name: Start
                show_state: false
              - type: button
                tap_action:
                  action: toggle
                entity: script.stop_vehicle
                name: Cancel Start
                show_state: false
                icon: 'mdi:car-off'
              - type: button
                tap_action:
                  action: toggle
                entity: script.lock_vehicle
                name: Lock
                show_state: false
                icon: 'mdi:car-door-lock'
              - type: button
                tap_action:
                  action: toggle
                entity: script.unlock_vehicle
                name: Unlock
                show_state: false
                icon: 'mdi:car-door'
              - type: button
                tap_action:
                  action: toggle
                entity: script.update_vehicle_info
                name: Update Info
                show_state: false
                icon: 'mdi:refresh'
              - type: button
                tap_action:
                  action: toggle
                entity: script.locate_vehicle
                name: Update Location
                show_state: false
                icon: 'mdi:map'
            columns: 3
```


Here is what it looks like
![image](https://user-images.githubusercontent.com/503761/197799397-4edbb78d-22bd-4cb8-a61f-a6cfafef0b01.png)
